### ISSUE TITLE
Counts 0 emails

### ISSUE THREAD

**Issue by lgatto** [sje30/yesterbox#1]
After cloning `yesterbox` and running
```el
(load-file "~/.emacs.d/yesterbox/yesterbox.el")
```
I run `M-x yesterbox` and get 

![2018-11-27-110640_150x140_scrot](https://user-images.githubusercontent.com/384198/49074205-8053d900-f234-11e8-8bc6-8a9d6dcfd2e3.png)

I appreciate the effort to reduce my email-related stress, but this is definitely wrong :-)

**Comment by sje30** [comment]
oh no!  thanks for testing.  can you see what the search is doing?

press "c" on the first line of that buffer - what do you see at the bottom?  that is the search it will execute. For me I get:

```
current line ID is: maildir:/inbox AND date:20181126
```

try the seach:

```
 maildir:/inbox AND date:20181126
```

have you changed the inbox by any chance?

**Comment by lgatto** [comment]
I get 
```
current line ID is: maildir:/inbox AND date:20181126
```
What do you mean by search? Running ` mu find date:20181126` on the command line returns a plausible number. 

Trying to figure out how to answer to your second question, I think the error results from the fact that I have 
```sh
$ ls Maildir
archive  account1 account2 account2 drafts  sent  trash 
```
And indeed, if I `yesterbox-search-string` with
```el
(defun yesterbox-search-string (n)
  "Return a mu search string to find inbox messages from N days ago.
If N is an integer, search for N days ago.
If N is a dotted pair (a . b), search for messages between a and b days ago."
  (if (consp n)
      (format "maildir:/acount1/inbox AND date:%s..%s"
	      (yesterbox-n-days-ago (cdr n))
	      (yesterbox-n-days-ago (car n)))
    (format "maildir:/account1/inbox AND date:%s" (yesterbox-n-days-ago n))))
```
or
```el
(defun yesterbox-search-string (n)
  "Return a mu search string to find inbox messages from N days ago.
If N is an integer, search for N days ago.
If N is a dotted pair (a . b), search for messages between a and b days ago."
  (if (consp n)
      (format "date:%s..%s"
	      (yesterbox-n-days-ago (cdr n))
	      (yesterbox-n-days-ago (car n)))
    (format "date:%s" (yesterbox-n-days-ago n))))
```
I get reasonable counts.

Could you define an optional `maildir` variable to either count emails from a specific inbox (like `maildir:/account1/inbox`), a single account (like `maildir:/inbox`) or all accounts (no `maildir:/` at all).

**Comment by sje30** [comment]
Thanks.  Now I see.  I'll add a variable as you suggest.  

BTW, not specifying a maildir at all means it will search all folders, right (not just your inboxes)?

**Comment by sje30** [comment]
hi Laurent, just fixed. see `yesterbox-inbox' which I think you should set to "account1/inbox" (at the moment no option to leave it blank, as they gets all mail from yesterday)

**Comment by lgatto** [comment]
Yes, `account1/inbox/` works, thank you. And indeed, not defining any inbox searches all folders (inbox, sent, trash, ...). 

To get my desired behaviour, setting the following seems to work

```el
(defvar yesterbox-inbox "inbox/"
  "*Name of your primary inbox.")
```
Indeed, from `man mu-query`:
```
Note  the difference between 'maildir:/foo' and 'maildir:/foo/'; the latter matches 
messages in the '/foo' maildir, while the latter matches all messages in all maildirs 
that match 'foo', such as '/foo', '/bar/cuux/foo', '/fooish-bar' etc.
```
